# Generated by Django 5.2.13 on 2026-05-28 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_cookingclass_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookingclass",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="joined_classes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
